set goup=%@char[30]%%@char[30]%
type a:\utils\cpuspeed.com^echo %goup%
type a:\utils\extclock.com^echo %goup%
type a:\utils\firminfo.com^echo %goup%
type a:\utils\getreset.com^echo %goup%
type a:\utils\keyboard.com^echo %goup%
type a:\utils\pldflash.com^echo %goup%
type a:\utils\setaudio.com^echo %goup%
type a:\utils\setsmart.com^echo %goup%
type a:\utils\slotmode.com^echo %goup%
type a:\utils\vdpspeed.com^echo %goup%
type a:\utils\vgaratio.com^echo %goup%
type a:\utils\smxflash.com^set goup=
